/**:
  ros__parameters:
    general:
      camera_model: 'zed2i'
      grab_resolution: 'HD2K'
      grab_frame_rate: 15
      pub_resolution: 'HD2k'
      pub_frame_rate: 15.0
      
    depth:
      depth_mode: 'NEURAL_PLUS'
      
    pos_tracking:
      pos_tracking_enabled: true
      publish_tf: true
      publish_map_tf: true
      area_memory: true
      mode: 'GEN_2'
      depth_stabilization: 1

    mapping:
      mapping_enabled: true
      resolution: 0.02
      max mapping range: 20.0