/**:
  ros__parameters:
    general:
      camera_model: 'zed2i'
      grab_resolution: 'HD1080'
      grab_frame_rate: 15
      pub_frame_rate: 15.0
      
    pos_tracking:
      pos_tracking_enabled: true
      publish_tf: true
      publish_map_tf: false
      area_memory: false
      mode: 'GEN_2'
      depth_stabilization: 1